name: Auto Sync Fork and PR

on:
  schedule:
    - cron: "0 0 * * *" # runs every day at midnight UTC
  workflow_dispatch: # manual trigger

jobs:
  sync-and-pr:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout your fork
      - name: Checkout fork
        uses: actions/checkout@v3
        with:
          repository: Sudhi-S-2003/Oxium-website
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # 2️⃣ Add upstream repo
      - name: Add upstream
        run: git remote add upstream https://github.com/sooraj-RK/Oxium-website.git

      # 3️⃣ Fetch upstream changes
      - name: Fetch upstream
        run: git fetch upstream

      # 4️⃣ Merge upstream -> main
      - name: Merge upstream into main
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories -m "Sync from upstream"
          git push origin main

      # 5️⃣ Create Pull Request automatically
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Sync fork with upstream"
          branch: main
          title: "Sync fork with upstream"
          body: "This PR syncs the fork with the original repository."
          base: main
          labels: "auto-sync"
          draft: false
